regen, as sequel to r5181
git-svn-id: https://svn.code.sf.net/p/gfarm/code/gfarm2fs/trunk@5182 4a5e1ece-6a47-475c-b646-731d720b41d0

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -20441,14 +20441,13 @@ echo "$as_me: error: libgfarm not found" >&2;}
    { (exit 1); exit 1; }; }
 fi
 
-
-echo "$as_me:$LINENO: checking for fuse_main in -lfuse" >&5
-echo $ECHO_N "checking for fuse_main in -lfuse... $ECHO_C" >&6
-if test "${ac_cv_lib_fuse_fuse_main+set}" = set; then
+echo "$as_me:$LINENO: checking for library containing fuse_opt_parse" >&5
+echo $ECHO_N "checking for library containing fuse_opt_parse... $ECHO_C" >&6
+if test "${ac_cv_search_fuse_opt_parse+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
-  ac_check_lib_save_LIBS=$LIBS
-LIBS="-lfuse  $LIBS"
+  ac_func_search_save_LIBS=$LIBS
+ac_cv_search_fuse_opt_parse=no
 cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
@@ -20462,11 +20461,11 @@ extern "C"
 #endif
 /* We use char because int might match the return type of a gcc2
    builtin and then its argument prototype would still apply.  */
-char fuse_main ();
+char fuse_opt_parse ();
 int
 main ()
 {
-fuse_main ();
+fuse_opt_parse ();
   ;
   return 0;
 }
@@ -20493,25 +20492,78 @@ if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
-  ac_cv_lib_fuse_fuse_main=yes
+  ac_cv_search_fuse_opt_parse="none required"
 else
   echo "$as_me: failed program was:" >&5
 sed 's/^/| /' conftest.$ac_ext >&5
 
-ac_cv_lib_fuse_fuse_main=no
 fi
 rm -f conftest.err conftest.$ac_objext \
       conftest$ac_exeext conftest.$ac_ext
-LIBS=$ac_check_lib_save_LIBS
-fi
-echo "$as_me:$LINENO: result: $ac_cv_lib_fuse_fuse_main" >&5
-echo "${ECHO_T}$ac_cv_lib_fuse_fuse_main" >&6
-if test $ac_cv_lib_fuse_fuse_main = yes; then
-  cat >>confdefs.h <<_ACEOF
-#define HAVE_LIBFUSE 1
+if test "$ac_cv_search_fuse_opt_parse" = no; then
+  for ac_lib in fuse refuse; do
+    LIBS="-l$ac_lib  $ac_func_search_save_LIBS"
+    cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
 _ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
 
-  LIBS="-lfuse $LIBS"
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char fuse_opt_parse ();
+int
+main ()
+{
+fuse_opt_parse ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_search_fuse_opt_parse="-l$ac_lib"
+break
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+  done
+fi
+LIBS=$ac_func_search_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_search_fuse_opt_parse" >&5
+echo "${ECHO_T}$ac_cv_search_fuse_opt_parse" >&6
+if test "$ac_cv_search_fuse_opt_parse" != no; then
+  test "$ac_cv_search_fuse_opt_parse" = "none required" || LIBS="$ac_cv_search_fuse_opt_parse $LIBS"
 
 else
   { { echo "$as_me:$LINENO: error: libfuse not found" >&5
@@ -20629,6 +20681,71 @@ _ACEOF
 
 fi
 done
+
+
+if test "$cross_compiling" = yes; then
+  { { echo "$as_me:$LINENO: error: cannot run test program while cross compiling
+See \`config.log' for more details." >&5
+echo "$as_me: error: cannot run test program while cross compiling
+See \`config.log' for more details." >&2;}
+   { (exit 1); exit 1; }; }
+else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+#  include <fuse.h>
+
+  void *data_save;
+
+  int opt_proc(void *data, const char *arg, int key, struct fuse_args *outargs)
+  {
+	  data_save = data;
+  }
+
+  int
+  main(int argc, char **argv)
+  {
+	  struct fuse_args args = FUSE_ARGS_INIT(argc, argv);
+	  int data;
+	  fuse_opt_parse(&args, &data, NULL, opt_proc);
+	  if (data_save == &data)
+		  return 1;
+	  return 0; /* have a bug on NetBSD */
+  }
+
+_ACEOF
+rm -f conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && { ac_try='./conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  cat >>confdefs.h <<\_ACEOF
+#define HAVE_BUG_OF_FUSE_OPT_PARSE_ON_NETBSD 1
+_ACEOF
+
+else
+  echo "$as_me: program exited with status $ac_status" >&5
+echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+( exit $ac_status )
+
+
+fi
+rm -f core *.core gmon.out bb.out conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
+fi
+
+
 
 
 cat >confcache <<\_ACEOF
