fixed following in test scripts(#538 Add more tests to make gfarm more stable)  * changed expected behaviour    * commands running on gfarm2fs cannot get return code of gfs_pio_close()    * gfs_pio_close() will be executed after execution of a command running      on gfarm2fs  * add more wait for gfsd get connected to gfmd
git-svn-id: https://svn.code.sf.net/p/gfarm/code/gfarm2fs/trunk@7912 4a5e1ece-6a47-475c-b646-731d720b41d0

diff --git a/systest/testcases/gfmd_ifdown_in_write b/systest/testcases/gfmd_ifdown_in_write
--- a/systest/testcases/gfmd_ifdown_in_write
+++ b/systest/testcases/gfmd_ifdown_in_write
@@ -61,9 +61,9 @@ test_gfmd_ifdown_in_write()
 	fi
 
 	wait $MAKE_PID
-	if [ $? -eq 0 ]; then
-		log_warn "$TESTNAME: unexpectedly succeeded to make a file"
-		set_result RESULT $RESULT_XPASS
+	if [ $? -ne 0 ]; then
+		log_warn "$TESTNAME: failed to make a file"
+		set_result RESULT $RESULT_XFAIL
 	fi
 
 	# step: make network interface up
@@ -107,9 +107,9 @@ test_gfmd_ifdown_in_write()
 
 	# step: check metadata filesize
 	check_metadata_filesize client1 $GFARM_FILE gfmd1
-	if [ $? -eq 0 ]; then
-		log_warn "$TESTNAME: unexpectedly metadata is updated"
-		set_result RESULT $RESULT_XPASS
+	if [ $? -ne 0 ]; then
+		log_warn "$TESTNAME: metadata is not updated"
+		set_result RESULT $RESULT_XFAIL
 	fi
 
 	# step: make files
