modified following in test script(#538 Add more tests to make gfarm more stable)  * changed result code  * fixed a mistake
git-svn-id: https://svn.code.sf.net/p/gfarm/code/gfarm2fs/trunk@7830 4a5e1ece-6a47-475c-b646-731d720b41d0

diff --git a/systest/testcases/gfmd_ifdown_in_read b/systest/testcases/gfmd_ifdown_in_read
--- a/systest/testcases/gfmd_ifdown_in_read
+++ b/systest/testcases/gfmd_ifdown_in_read
@@ -63,9 +63,9 @@ test_gfmd_ifdown_in_read()
 	fi
 
 	wait $READ_PID
-	if [ $? -eq 0 ]; then
-		log_warn "$TESTNAME: unexpectedly suceeded to read a file"
-		RESULT=$RESULT_XPASS
+	if [ $? -ne 0 ]; then
+		log_warn "$TESTNAME: failed to read a file"
+		RESULT=$RESULT_FAIL
 	fi
 
 	# step: make network interface up
