'make_dir' and 'make_file' testcases of 'systest' now check whether the current user belongs to 'gfarmroot' group.
git-svn-id: https://svn.code.sf.net/p/gfarm/code/gfarm2fs/trunk@8514 4a5e1ece-6a47-475c-b646-731d720b41d0

diff --git a/systest/testcases/make_file b/systest/testcases/make_file
--- a/systest/testcases/make_file
+++ b/systest/testcases/make_file
@@ -1,13 +1,14 @@
 #
 # Test case for making files
 #
-load	"gfarm_v2::check_replica_num"
+load	"gfarm_v2::check_replica_num" \
+	"gfarm2fs::check_user_group"
 
 #
 # Test parameters
 #
 # GFARM_HOME:	A directory path of Gfarm which this test will be executed
-# RETRY_COUNT:»-Retry number to check replica
+# RETRY_COUNT:	Retry number to check replica
 #
 setup_make_file()
 {
@@ -23,6 +24,9 @@ setup_make_file()
 	if [ X$AUTH_TYPE = Xgsi ] || [ X$AUTH_TYPE = Xgsi_auth ]; then
 		$GFSERVICE systest::gfarm_v2::grid_proxy_init client1
 	fi
+
+	# prepare: check whether the user belongs to 'gfarmtoot' group
+	check_user_group client1 - gfarmroot || return $RESULT_UNSUPPORTED
 
 	# prepare: set file replica to be created
 	$GFSERVICE gfcmd client1 gfncopy -s 2 $GFARM_HOME
