Introduce name spaces in 'systest' and separate installation directories of 'systest' files of gfarm_v2 and gfarm2fs packages. (#699)
git-svn-id: https://svn.code.sf.net/p/gfarm/code/gfarm2fs/trunk@8220 4a5e1ece-6a47-475c-b646-731d720b41d0

diff --git a/systest/plugins/check_files_n_each_mntpnts b/systest/plugins/check_files_n_each_mntpnts
--- a/systest/plugins/check_files_n_each_mntpnts
+++ b/systest/plugins/check_files_n_each_mntpnts
@@ -15,8 +15,8 @@ subcmd_check_files_n_each_mntpnts()
 
 	check_argc $# 5
 	check_hostid any $HOSTID
-	exec_remote_host_agent $HOSTID - check_files_n_each_mntpnts "$@"
-	[ $? -ne 0 ] && log_error "gfservice check_files_n_each_mntpnts failed"
+	exec_remote_host_agent $HOSTID - systest::gfarm2fs::check_files_n_each_mntpnts "$@"
+	[ $? -ne 0 ] && log_error "gfservice systest::gfarm2fs::check_files_n_each_mntpnts failed"
 
 	log_debug "end subcmd_check_files_n_each_mntpnts"
 }
@@ -26,11 +26,11 @@ subcmd_check_files_n_each_mntpnts()
 #
 check_files_n_each_mntpnts_agent_depends()
 {
-	echo "check_files"
+	echo "systest::gfarm2fs::check_files"
 }
 
 #
-# Sub-command: check_files_n_each_mntpnts
+# Sub-command: systest::gfarm2fs::check_files_n_each_mntpnts
 # Check files in target dir on each mount points.
 #
 subcmd_check_files_n_each_mntpnts_agent()
diff --git a/systest/plugins/make_files b/systest/plugins/make_files
--- a/systest/plugins/make_files
+++ b/systest/plugins/make_files
@@ -15,8 +15,8 @@ subcmd_make_files()
 
 	check_argc $# 3
 	check_hostid any $HOSTID
-	exec_remote_host_agent $HOSTID - make_files "$@"
-	[ $? -ne 0 ] && log_error "gfservice make_files failed"
+	exec_remote_host_agent $HOSTID - systest::gfarm2fs::make_files "$@"
+	[ $? -ne 0 ] && log_error "gfservice systest::gfarm2fs::make_files failed"
 
 	log_debug "end subcmd_make_files"
 }
@@ -45,11 +45,11 @@ make_files()
 #
 make_files_agent_depends()
 {
-	echo "make_file"
+	echo "systest::gfarm2fs::make_file"
 }
 
 #
-# Sub-command: make_files
+# Sub-command: systest::gfarm2fs::make_files
 # Make files in target dir.
 #
 subcmd_make_files_agent()
diff --git a/systest/plugins/make_files_n b/systest/plugins/make_files_n
--- a/systest/plugins/make_files_n
+++ b/systest/plugins/make_files_n
@@ -15,8 +15,8 @@ subcmd_make_files_n()
 
 	check_argc $# 5
 	check_hostid any $HOSTID
-	exec_remote_host_agent $HOSTID - make_files_n "$@"
-	[ $? -ne 0 ] && log_error "gfservice make_files_n failed"
+	exec_remote_host_agent $HOSTID - systest::gfarm2fs::make_files_n "$@"
+	[ $? -ne 0 ] && log_error "gfservice systest::gfarm2fs::make_files_n failed"
 
 	log_debug "end subcmd_make_files_n"
 }
@@ -26,11 +26,12 @@ subcmd_make_files_n()
 #
 make_files_n_agent_depends()
 {
-	echo "make_file make_files"
+	echo "systest::gfarm2fs::make_file"
+	echo "systest::gfarm2fs::make_files"
 }
 
 #
-# Sub-command: make_files_n
+# Sub-command: systest::gfarm2fs::make_files_n
 # Make files in target dir.
 #
 subcmd_make_files_n_agent()
diff --git a/systest/plugins/make_files_n_each_mntpnts b/systest/plugins/make_files_n_each_mntpnts
--- a/systest/plugins/make_files_n_each_mntpnts
+++ b/systest/plugins/make_files_n_each_mntpnts
@@ -15,8 +15,8 @@ subcmd_make_files_n_each_mntpnts()
 
 	check_argc $# 5
 	check_hostid any $HOSTID
-	exec_remote_host_agent $HOSTID - make_files_n_each_mntpnts "$@"
-	[ $? -ne 0 ] && log_error "gfservice make_files_n_each_mntpnts failed"
+	exec_remote_host_agent $HOSTID - systest::gfarm2fs::make_files_n_each_mntpnts "$@"
+	[ $? -ne 0 ] && log_error "gfservice systest::gfarm2fs::make_files_n_each_mntpnts failed"
 
 	log_debug "end subcmd_make_files_n_each_mntpnts"
 }
@@ -26,11 +26,12 @@ subcmd_make_files_n_each_mntpnts()
 #
 make_files_n_each_mntpnts_agent_depends()
 {
-	echo "make_file make_files"
+	echo "systest::gfarm2fs::make_file"
+	echo "systest::gfarm2fs::make_files"
 }
 
 #
-# Sub-command: make_files_n_each_mntpnts
+# Sub-command: systest::gfarm2fs::make_files_n_each_mntpnts
 # Make files in target dir on each mount points.
 #
 subcmd_make_files_n_each_mntpnts_agent()
diff --git a/systest/plugins/read_files b/systest/plugins/read_files
--- a/systest/plugins/read_files
+++ b/systest/plugins/read_files
@@ -15,8 +15,8 @@ subcmd_read_files()
 
 	check_argc $# 2
 	check_hostid any $HOSTID
-	exec_remote_host_agent $HOSTID - read_files "$@"
-	[ $? -ne 0 ] && log_error "gfservice read_files failed"
+	exec_remote_host_agent $HOSTID - systest::gfarm2fs::read_files "$@"
+	[ $? -ne 0 ] && log_error "gfservice systest::gfarm2fs::read_files failed"
 
 	log_debug "end subcmd_read_files"
 }
@@ -47,7 +47,7 @@ read_files()
 #
 read_files_agent_depends()
 {
-	echo "read_file"
+	echo "systest::gfarm2fs::read_file"
 }
 
 #
diff --git a/systest/plugins/read_files_n b/systest/plugins/read_files_n
--- a/systest/plugins/read_files_n
+++ b/systest/plugins/read_files_n
@@ -15,8 +15,8 @@ subcmd_read_files_n()
 
 	check_argc $# 4
 	check_hostid any $HOSTID
-	exec_remote_host_agent $HOSTID - read_files_n "$@"
-	[ $? -ne 0 ] && log_error "gfservice read_files_n failed"
+	exec_remote_host_agent $HOSTID - systest::gfarm2fs::read_files_n "$@"
+	[ $? -ne 0 ] && log_error "gfservice systest::gfarm2fs::read_files_n failed"
 
 	log_debug "end subcmd_read_files_n"
 }
@@ -26,11 +26,12 @@ subcmd_read_files_n()
 #
 read_files_n_agent_depends()
 {
-	echo "read_file read_files"
+	echo "systest::gfarm2fs::read_file"
+	echo "systest::gfarm2fs::read_files"
 }
 
 #
-# Sub-command: read_files_n
+# Sub-command: systest::gfarm2fs::read_files_n
 # Read files in target dir.
 #
 subcmd_read_files_n_agent()
diff --git a/systest/plugins/remove_files_each_mntpnts b/systest/plugins/remove_files_each_mntpnts
--- a/systest/plugins/remove_files_each_mntpnts
+++ b/systest/plugins/remove_files_each_mntpnts
@@ -15,8 +15,8 @@ subcmd_remove_files_each_mntpnts()
 
 	check_argc $# 4
 	check_hostid any $HOSTID
-	exec_remote_host_agent $HOSTID - remove_files_each_mntpnts "$@"
-	[ $? -ne 0 ] && log_error "gfservice remove_files_each_mntpnts failed"
+	exec_remote_host_agent $HOSTID - systest::gfarm2fs::remove_files_each_mntpnts "$@"
+	[ $? -ne 0 ] && log_error "gfservice systest::gfarm2fs::remove_files_each_mntpnts failed"
 
 	log_debug "end subcmd_remove_files_each_mntpnts"
 }
@@ -26,7 +26,7 @@ subcmd_remove_files_each_mntpnts()
 #
 remove_files_each_mntpnts_agent_depends()
 {
-	echo "remove_files"
+	echo "systest::gfarm2fs::remove_files"
 }
 
 #
