add scripts for testing behavior when server is down(#538 Add more tests to make gfarm more stable)
git-svn-id: https://svn.code.sf.net/p/gfarm/code/gfarm2fs/trunk@7631 4a5e1ece-6a47-475c-b646-731d720b41d0

diff --git a/systest/plugins/exec_ssh b/systest/plugins/exec_ssh
--- a/systest/plugins/exec_ssh
+++ b/systest/plugins/exec_ssh
@@ -22,8 +22,9 @@ subcmd_exec_ssh()
 
 	log_debug "subcmd_ssh: execute $SSH $HOST $@"
 	$SSH $HOST "$@"
-	RESULT=$?
+	if [ $? -ne 0 ]; then
+		log_error "command execution failed"
+	fi
 
 	log_debug "end subcmd_ssh"
-	return $RESULT
 }
