Output a log message when a 'systest' plugin of 'gfservice' performs 'mkdir'.
git-svn-id: https://svn.code.sf.net/p/gfarm/code/gfarm2fs/trunk@8651 4a5e1ece-6a47-475c-b646-731d720b41d0

diff --git a/systest/plugins/make_files b/systest/plugins/make_files
--- a/systest/plugins/make_files
+++ b/systest/plugins/make_files
@@ -29,6 +29,8 @@ make_files()
 
 	if [ ! -d $TARGET_DIR ]; then
 		mkdir -p $TARGET_DIR
+		[ $? -ne 0 ] && log_error "mkdir -p $TARGET_DIR failed"
+		log_debug "mkdir -p $TARGET_DIR"
 	fi
 
 	for I in `seq $NUM_FILES` ; do
diff --git a/systest/plugins/mkdir_n b/systest/plugins/mkdir_n
--- a/systest/plugins/mkdir_n
+++ b/systest/plugins/mkdir_n
@@ -44,7 +44,8 @@ subcmd_mkdir_n_agent()
 		DIR=`printf $DIR_PREFIX%04d $I`
 		if [ ! -d $DIR ]; then
 			mkdir -p $DIR
-			[ $? -ne 0 ] && log_error "failed to mkdir $DIR"
+			[ $? -ne 0 ] && log_error "failed to mkdir -p $DIR"
+			log_debug "mkdir -p $DIR"
 		fi
 	done
 
