add/modify test cases(#538 Add more tests to make gfarm more stable)  * add test cases to check behavior when two gfsd node is down  * add step to check file size saved in metadata  * add step to compare checksum  * fixed log messages
git-svn-id: https://svn.code.sf.net/p/gfarm/code/gfarm2fs/trunk@7745 4a5e1ece-6a47-475c-b646-731d720b41d0

diff --git a/systest/plugins/read_file b/systest/plugins/read_file
--- a/systest/plugins/read_file
+++ b/systest/plugins/read_file
@@ -13,7 +13,7 @@ subcmd_read_file()
 {
 	log_debug "subcmd_read_file"
 
-	check_argc $# 1
+	check_argc $# 1 +
 	check_hostid $HOSTID
 	exec_client_host_agent $HOSTID - read_file "$@"
 	[ $? -ne 0 ] && log_error "gfservice read_file failed"
@@ -24,9 +24,18 @@ subcmd_read_file()
 read_file()
 {
 	FILE_PATH=$1
+	CHECKSUM_EXPECTED=$2
 
-	dd if=$FILE_PATH of=/dev/null 2>/dev/null
-	[ $? -ne 0 ] && log_error "failed to read file: $FILE_PATH"
+	if [ X$CHECKSUM_EXPECTED = X ]; then
+		dd if=$FILE_PATH of=/dev/null 2>/dev/null
+		[ $? -ne 0 ] && log_error "failed to read file: $FILE_PATH"
+	else
+		CHECKSUM_ACTUAL`dd if=$FILE_PATH | openssl md5`
+		[ $? -ne 0 ] && log_error "failed to read file: $FILE_PATH"
+		[ $CHECKSUM_ACTUAL != $CHECKSUM_EXPECTED ] \
+			log_error "checksum of a file $FILE_PATH is not same" \
+				"to expected one"
+	fi
 	log_debug "$PROGHOST read $FILE_PATH done"
 }
 
diff --git a/systest/testcases/delete_in_two_gfsd_ifdown b/systest/testcases/delete_in_two_gfsd_ifdown
--- a/systest/testcases/delete_in_two_gfsd_ifdown
+++ b/systest/testcases/delete_in_two_gfsd_ifdown
@@ -1,6 +1,6 @@
 #
-# Test case for deleting a file which has replication, when gfsd network
-# interface is down
+# Test case for deleting a file which has replication, when network
+# interface of two gfsd node is down
 #
 load	"wait_for_gfsd_disconnect"
 
@@ -12,7 +12,7 @@ load	"wait_for_gfsd_disconnect"
 # RETRY_COUNT:		Retry number to check gfsd connection or number of
 #			replicas
 # RETRY_INTERVAL:	Retry interval(sec) to check gfsd connection
-test_delete_in_gfsd_ifdown()
+test_delete_in_two_gfsd_ifdown()
 {
 	RESULT=$RESULT_PASS
 
@@ -20,10 +20,11 @@ test_delete_in_gfsd_ifdown()
 	GFARM_HOME=${GFARM_HOME-"/"}
 	FILE_SIZE=${FILE_SIZE-"100M"}
 	RETRY_COUNT=${RETRY_COUNT-"10"}
-	RETRY_INTERVAL=${RETRY_INTERVAL-"5"}
+	RETRY_INTERVAL=${RETRY_INTERVAL-"10"}
 
 	# prepare: check whether required hosts are defined
-	$GFSERVICE $DEBUG check_hostids_defined - "gfmd1 gfsd1 gfsd2 client1"
+	$GFSERVICE $DEBUG check_hostids_defined - \
+		"gfmd1 gfsd1 gfsd2 gfsd3 client1"
 	[ $? -ne 0 ] && return $RESULT_UNSUPPORTED
 
 	AUTH_TYPE=`$GFSERVICE $DEBUG get-config-gfarm-param gfmd1 AUTH_TYPE`
@@ -32,28 +33,50 @@ test_delete_in_gfsd_ifdown()
 	fi
 
 	# prepare: make a file with replica
-	GFARM_FILE=$GFARM_HOME/$TEST_EXEC_ID
+	GFARM_FILE1=$GFARM_HOME/${TEST_EXEC_ID}_1
 	dd if=/dev/zero bs=$FILE_SIZE count=1 | tr "\000" "a" | \
 		$GFSERVICE $DEBUG read_and_register client1 \
-		$GFARM_FILE gfmd1 gfsd1
+		$GFARM_FILE1 gfmd1 gfsd1
 	if [ $? -ne 0 ]; then
 		log_warn "$TESTNAME: failed to register file on gfsd1"
 		return $RESULT_FATAL
 	fi
 
-	$GFSERVICE $DEBUG replicate_file client1 $GFARM_FILE gfsd2
+	$GFSERVICE $DEBUG replicate_file client1 $GFARM_FILE1 gfsd3
 	if [ $? -ne 0 ]; then
-		log_warn "$TESTNAME: failed to replicate file on gfsd2"
+		log_warn "$TESTNAME: failed to replicate file on gfsd3"
+		return $RESULT_FATAL
+	fi
+
+	GFARM_FILE2=$GFARM_HOME/${TEST_EXEC_ID}_2
+	dd if=/dev/zero bs=$FILE_SIZE count=1 | tr "\000" "a" | \
+		$GFSERVICE $DEBUG read_and_register client1 \
+		$GFARM_FILE2 gfmd1 gfsd2
+	if [ $? -ne 0 ]; then
+		log_warn "$TESTNAME: failed to register file on gfsd2"
+		return $RESULT_FATAL
+	fi
+
+	$GFSERVICE $DEBUG replicate_file client1 $GFARM_FILE2 gfsd3
+	if [ $? -ne 0 ]; then
+		log_warn "$TESTNAME: failed to replicate file on gfsd3"
 		return $RESULT_FATAL
 	fi
 
 	# prepare: get spool file path
-	SPOOL_PATH=`$GFSERVICE $DEBUG gfcmd client1 gfspoolpath $GFARM_FILE`
+	SPOOL_PATH1=`$GFSERVICE $DEBUG gfcmd client1 gfspoolpath $GFARM_FILE1`
+	SPOOL_PATH2=`$GFSERVICE $DEBUG gfcmd client1 gfspoolpath $GFARM_FILE2`
 
 	# prepare: make network interface down
 	$GFSERVICE $DEBUG ifdown gfsd1
 	if [ $? -ne 0 ]; then
 		log_warn "$TESTNAME: failed to execute ifdown on gfsd1"
+		return $RESULT_FATAL
+	fi
+
+	$GFSERVICE $DEBUG ifdown gfsd2
+	if [ $? -ne 0 ]; then
+		log_warn "$TESTNAME: failed to execute ifdown on gfsd2"
 		return $RESULT_FATAL
 	fi
 
@@ -64,15 +87,27 @@ test_delete_in_gfsd_ifdown()
 		return $RESULT_FATAL
 	fi
 
+	wait_for_gfsd_disconnect gfsd2 client1 $RETRY_COUNT $RETRY_INTERVAL
+	if [ $? -eq 0 ]; then
+		log_warn "$TESTNAME: gfsd2 is available unexpectedly"
+		return $RESULT_FATAL
+	fi
+
 	# step: remove file
-	$GFSERVICE $DEBUG gfcmd client1 gfrm -f $GFARM_FILE
+	$GFSERVICE $DEBUG gfcmd client1 gfrm -f $GFARM_FILE1 $GFARM_FILE2
 	if [ $? -ne 0 ]; then
 		log_warn "$TESTNAME: failed to remove a file"
 		RESULT=$RESULT_FAIL
 	fi
 
 	# step: check spool file
-	$GFSERVICE $DEBUG spool_file_exists gfsd2 $SPOOL_PATH
+	$GFSERVICE $DEBUG spool_file_exists gfsd3 $SPOOL_PATH1
+	if [ $? -eq 0 ]; then
+		log_warn "$TESTNAME: a spool file remains"
+		RESULT=$RESULT_FAIL
+	fi
+
+	$GFSERVICE $DEBUG spool_file_exists gfsd3 $SPOOL_PATH2
 	if [ $? -eq 0 ]; then
 		log_warn "$TESTNAME: a spool file remains"
 		RESULT=$RESULT_FAIL
@@ -85,8 +120,20 @@ test_delete_in_gfsd_ifdown()
 		return $RESULT_FATAL
 	fi
 
+	$GFSERVICE $DEBUG ifup gfsd2
+	if [ $? -ne 0 ]; then
+		log_warn "$TESTNAME: failed to execute ifup on gfsd2"
+		return $RESULT_FATAL
+	fi
+
 	# step: check original spool file remains
-	$GFSERVICE $DEBUG spool_file_exists gfsd1 $SPOOL_PATH
+	$GFSERVICE $DEBUG spool_file_exists gfsd1 $SPOOL_PATH1
+	if [ $? -ne 0 ]; then
+		log_warn "$TESTNAME: cannot find a spool file"
+		RESULT=$RESULT_FAIL
+	fi
+
+	$GFSERVICE $DEBUG spool_file_exists gfsd2 $SPOOL_PATH2
 	if [ $? -ne 0 ]; then
 		log_warn "$TESTNAME: cannot find a spool file"
 		RESULT=$RESULT_FAIL
diff --git a/systest/testcases/gfmd_ifdown_in_write b/systest/testcases/gfmd_ifdown_in_write
--- a/systest/testcases/gfmd_ifdown_in_write
+++ b/systest/testcases/gfmd_ifdown_in_write
@@ -2,6 +2,8 @@
 # Test case for check behavior when gfmd network interface is down
 # in writing files
 #
+load	"calc_checksum" \
+	"check_metadata_filesize"
 
 #
 # Test parameters
@@ -26,6 +28,9 @@ test_gfmd_ifdown_in_write()
 	if [ X$AUTH_TYPE = Xgsi ] || [ X$AUTH_TYPE = Xgsi_auth ]; then
 		$GFSERVICE $DEBUG grid_proxy_init client1
 	fi
+
+	# prepare: calc checksum
+	CHECKSUM_EXPECT=`calc_checksum $FILE_SIZE`
 
 	# prepare: mount
 	MOUNT_POINT=mnt_$TEST_EXEC_ID
@@ -75,10 +80,75 @@ test_gfmd_ifdown_in_write()
 		return $RESULT_FATAL
 	fi
 
+	# step: compare check sum of spool file
+	GFARM_FILE=$GFARM_HOME/$TEST_EXEC_ID
+	SPOOL_PATH=`$GFSERVICE $DEBUG gfcmd client1 gfspoolpath $GFARM_FILE`
+	if [ X$SPOOL_PATH = X ]; then
+		log_warn "$TESTNAME: failed to get spool path"
+		return $RESULT_FATAL
+	fi
+
+	for HOST in `$GFSERVICE $DEBUG gfcmd client1 gfwhere $GFARM_FILE`; do
+		HOSTID=`$GFSERVICE $DEBUG get_hostid $HOST`
+		CHECKSUM_ACTUAL=`$GFSERVICE $DEBUG spool_file_checksum $HOSTID \
+			 $SPOOL_PATH`
+		if [ X$CHECKSUM_ACTUAL = X ]; then
+			log_warn "$TESTNAME: fail to get checksum of a spool" \
+				"file on $HOST"
+			RESULT=$RESULT_FAIL
+		fi
+
+		if [ X$CHECKSUM_ACTUAL != X$CHECKSUM ]; then
+			log_warn "$TESTNAME: checksum of file is different to" \
+				"original one"
+			RESULT=$RESULT_FAIL
+		fi
+	done
+
+	# step: check metadata filesize
+	check_metadata_filesize client1 $GFARM_FILE gfmd1
+	if [ $? -ne 0 ]; then
+		log_warn "$TESTNAME: file size of metadata is not same to" \
+			"actual one"
+		RESULT=$RESULT_XFAIL
+	fi
+
 	# step: make files
 	$GFSERVICE $DEBUG make_file client1 $FILE_PATH $FILE_SIZE
 	if [ $? -ne 0 ]; then
 		log_warn "$TESTNAME: failed to make a file"
+		RESULT=$RESULT_FAIL
+	fi
+
+	# step: compare check sum of spool file
+	SPOOL_PATH=`$GFSERVICE $DEBUG gfcmd client1 gfspoolpath $GFARM_FILE`
+	if [ X$SPOOL_PATH = X ]; then
+		log_warn "$TESTNAME: failed to get spool path"
+		return $RESULT_FATAL
+	fi
+
+	for HOST in `$GFSERVICE $DEBUG gfcmd client1 gfwhere $GFARM_FILE`; do
+		HOSTID=`$GFSERVICE $DEBUG get_hostid $HOST`
+		CHECKSUM_ACTUAL=`$GFSERVICE $DEBUG spool_file_checksum $HOSTID \
+			 $SPOOL_PATH`
+		if [ X$CHECKSUM_ACTUAL = X ]; then
+			log_warn "$TESTNAME: fail to get checksum of a spool" \
+				"file on $HOST"
+			RESULT=$RESULT_FAIL
+		fi
+
+		if [ X$CHECKSUM_ACTUAL != X$CHECKSUM ]; then
+			log_warn "$TESTNAME: checksum of file is different to" \
+				"original one"
+			RESULT=$RESULT_FAIL
+		fi
+	done
+
+	# step: check metadata filesize
+	check_metadata_filesize client1 $GFARM_FILE gfmd1
+	if [ $? -ne 0 ]; then
+		log_warn "$TESTNAME: file size of metadata is not same to" \
+			"actual one"
 		RESULT=$RESULT_FAIL
 	fi
 
diff --git a/systest/testcases/make_dir b/systest/testcases/make_dir
--- a/systest/testcases/make_dir
+++ b/systest/testcases/make_dir
@@ -30,11 +30,19 @@ test_make_dir()
 	fi
 
 	# step: gfchown
-	$GFSERVICE $DEBUG gfcmd client1 gfchown `id -un`:gfarmadm \
+	$GFSERVICE $DEBUG gfcmd client1 gfchown `id -un` \
 		$GFARM_HOME/$TEST_EXEC_ID
 	if [ $? -ne 0 ]; then
 		log_warn "$TESTNAME: gfchown failed"
 		RESULT=$RESULT_FAIL
+	fi
+
+	# step: gfchgrp
+	$GFSERVICE $DEBUG gfcmd client1 gfchgrp gfarmadm \
+		$GFARM_HOME/$TEST_EXEC_ID
+	if [ $? -ne 0 ]; then
+		log_warn "$TESTNAME: gfchgrp failed"
+		RESULT=1
 	fi
 
 	# step: gfchmod
diff --git a/systest/testcases/operation_in_pgsql_down b/systest/testcases/operation_in_pgsql_down
--- a/systest/testcases/operation_in_pgsql_down
+++ b/systest/testcases/operation_in_pgsql_down
@@ -1,6 +1,7 @@
 #
 # Test case for operation when backend db is down
 #
+load	"check_metadata_filesize"
 
 #
 # Test parameters
@@ -22,6 +23,9 @@ test_operation_in_pgsql_down()
 	if [ X$AUTH_TYPE = Xgsi ] || [ X$AUTH_TYPE = Xgsi_auth ]; then
 		$GFSERVICE $DEBUG grid_proxy_init client1
 	fi
+
+	# prepare: calc checksum
+	CHECKSUM_EXPECT=`echo $TEST_EXEC_ID | openssl md5 | awk '{ print $2 }`
 
 	# prepare: create mount point
 	MOUNT_POINT=mnt_$TEST_EXEC_ID
@@ -58,10 +62,49 @@ test_operation_in_pgsql_down()
 		RESULT=$RESULT_FAIL
 	fi
 
+	# step: compare check sum of spool file
+	SPOOL_PATH=`$GFSERVICE $DEBUG gfcmd client1 gfspoolpath $GFARM_FILE2`
+	if [ X$SPOOL_PATH = X ]; then
+		log_warn "$TESTNAME: failed to get spool path"
+		return $RESULT_FATAL
+	fi
+
+	for HOST in `$GFSERVICE $DEBUG gfcmd client1 gfwhere $GFARM_FILE2`; do
+		HOSTID=`$GFSERVICE $DEBUG get_hostid $HOST`
+		CHECKSUM_ACTUAL=`$GFSERVICE $DEBUG spool_file_checksum $HOSTID \
+			 $SPOOL_PATH`
+		if [ X$CHECKSUM_ACTUAL = X ]; then
+			log_warn "$TESTNAME: fail to get checksum of a spool" \
+				"file on $HOST"
+			RESULT=$RESULT_FAIL
+		fi
+
+		if [ X$CHECKSUM_ACTUAL != X$CHECKSUM ]; then
+			log_warn "$TESTNAME: checksum of file is different to" \
+				"original one"
+			RESULT=$RESULT_FAIL
+		fi
+	done
+
+	# step: check metadata filesize
+	check_metadata_filesize client1 $GFARM_FILE gfmd1
+	if [ $? -ne 0 ]; then
+		log_warn "$TESTNAME: file size of metadata is not same to" \
+			"actual one"
+		RESULT=$RESULT_FAIL
+	fi
+
 	# step: read file with gfexport
-	$GFSERVICE $DEBUG export_file client1 $GFARM_FILE1 gfmd1
+	CHECKSUM_ACTUAL=`$GFSERVICE $DEBUG export_file client1 $GFARM_FILE1 \
+		gfmd1 | openssl md5 | awk '{ print $2 }'`
 	if [ $? -ne 0 ]; then
 		log_warn "$TESTNAME: failed to read a file"
+		RESULT=$RESULT_FAIL
+	fi
+
+	if [ X$CHECKSUM_ACTUAL != X$CHECKSUM ]; then
+		log_warn "$TESTNAME: checksum of file is different to" \
+			"original one"
 		RESULT=$RESULT_FAIL
 	fi
 
@@ -122,10 +165,49 @@ test_operation_in_pgsql_down()
 		RESULT=$RESULT_FAIL
 	fi
 
-	# step: read file with gfexport
-	$GFSERVICE $DEBUG export_file client1 $GFARM_FILE1 gfmd1
+	# step: compare check sum of spool file
+	SPOOL_PATH=`$GFSERVICE $DEBUG gfcmd client1 gfspoolpath $GFARM_FILE2`
+	if [ X$SPOOL_PATH = X ]; then
+		log_warn "$TESTNAME: failed to get spool path"
+		return $RESULT_FATAL
+	fi
+
+	for HOST in `$GFSERVICE $DEBUG gfcmd client1 gfwhere $GFARM_FILE2`; do
+		HOSTID=`$GFSERVICE $DEBUG get_hostid $HOST`
+		CHECKSUM_ACTUAL=`$GFSERVICE $DEBUG spool_file_checksum $HOSTID \
+			 $SPOOL_PATH`
+		if [ X$CHECKSUM_ACTUAL = X ]; then
+			log_warn "$TESTNAME: fail to get checksum of a spool" \
+				"file on $HOST"
+			RESULT=$RESULT_FAIL
+		fi
+
+		if [ X$CHECKSUM_ACTUAL != X$CHECKSUM ]; then
+			log_warn "$TESTNAME: checksum of file is different to" \
+				"original one"
+			RESULT=$RESULT_FAIL
+		fi
+	done
+
+	# step: check metadata filesize
+	check_metadata_filesize client1 $GFARM_FILE gfmd1
 	if [ $? -ne 0 ]; then
-		log_warn "$TESTNAME: failed to read files"
+		log_warn "$TESTNAME: file size of metadata is not same to" \
+			"actual one"
+		RESULT=$RESULT_FAIL
+	fi
+
+	# step: read file with gfexport
+	CHECKSUM_ACTUAL=`$GFSERVICE $DEBUG export_file client1 $GFARM_FILE1 \
+		gfmd1 | openssl md5 | awk '{ print $2 }'`
+	if [ $? -ne 0 ]; then
+		log_warn "$TESTNAME: failed to read a file"
+		RESULT=$RESULT_FAIL
+	fi
+
+	if [ X$CHECKSUM_ACTUAL != X$CHECKSUM ]; then
+		log_warn "$TESTNAME: checksum of file is different to" \
+			"original one"
 		RESULT=$RESULT_FAIL
 	fi
 
diff --git a/systest/testcases/two_gfsd_ifdown_in_read b/systest/testcases/two_gfsd_ifdown_in_read
--- a/systest/testcases/two_gfsd_ifdown_in_read
+++ b/systest/testcases/two_gfsd_ifdown_in_read
@@ -1,7 +1,8 @@
 #
-# Test case for check behavior when gfsd network interface is down
-# in writing files
+# Test case for check behavior when network interface of two gfsd node is
+# down in reading files
 #
+load	"calc_checksum"
 
 #
 # Test parameters
@@ -9,7 +10,7 @@
 # GFARM_HOME:	A directory path of Gfarm which this test will be executed
 # FILE_SIZE:	Size of a file to be created
 # SLEEP_SEC:	Second to sleep before make network interface down
-test_gfsd_ifdown_in_write()
+test_two_gfsd_ifdown_in_read()
 {
 	RESULT=$RESULT_PASS
 
@@ -19,7 +20,7 @@ test_gfsd_ifdown_in_write()
 	SLEEP_SEC=${SLEEP_SEC-"3"}
 
 	# prepare: check whether required host is defined
-	$GFSERVICE $DEBUG check_hostids_defined - "gfmd1 gfsd1 client1"
+	$GFSERVICE $DEBUG check_hostids_defined - "gfmd1 gfsd1 gfsd2 client1"
 	[ $? -ne 0 ] && return $RESULT_UNSUPPORTED
 
 	AUTH_TYPE=`$GFSERVICE $DEBUG get-config-gfarm-param gfmd1 AUTH_TYPE`
@@ -27,20 +28,36 @@ test_gfsd_ifdown_in_write()
 		$GFSERVICE $DEBUG grid_proxy_init client1
 	fi
 
+	# prepare: calc checksum
+	CHECKSUM=`calc_checksum $FILE_SIZE`
+
 	# prepare: mount
 	MOUNT_POINT=mnt_$TEST_EXEC_ID
 	$GFSERVICE $DEBUG exec_ssh client1 mkdir $MOUNT_POINT
 	$GFSERVICE $DEBUG mount client1 $MOUNT_POINT -o modules=subdir \
 		-o subdir=$GFARM_HOME
 
-	# step: make files in background
+	# prepare: make file
 	GFARM_FILE1=$GFARM_HOME/${TEST_EXEC_ID}_1
 	dd if=/dev/zero bs=$FILE_SIZE count=1 | tr "\000" "a" | \
 		$GFSERVICE $DEBUG read_and_register client1 $GFARM_FILE1 \
-		gfmd1 gfsd1 &
-	MAKE_PID=$!
+		gfmd1 gfsd1
 
-	# wait a bit for a process starts making files
+	GFARM_FILE2=$GFARM_HOME/${TEST_EXEC_ID}_2
+	dd if=/dev/zero bs=$FILE_SIZE count=1 | tr "\000" "a" | \
+		$GFSERVICE $DEBUG read_and_register client1 $GFARM_FILE2 \
+		gfmd1 gfsd2
+
+	# step: read files in background
+	FILE_PATH1=$MOUNT_POINT/${TEST_EXEC_ID}_1
+	$GFSERVICE $DEBUG read_file client1 $FILE_PATH1 &
+	READ_PID1=$!
+
+	FILE_PATH2=$MOUNT_POINT/${TEST_EXEC_ID}_2
+	$GFSERVICE $DEBUG read_file client1 $FILE_PATH2 &
+	READ_PID2=$!
+
+	# wait a bit for a process starts reading files
 	sleep $SLEEP_SEC
 
 	# step: make network interface down
@@ -50,9 +67,23 @@ test_gfsd_ifdown_in_write()
 		return $RESULT_FATAL
 	fi
 
-	wait $MAKE_PID
+	$GFSERVICE $DEBUG ifdown gfsd2
+	if [ $? -ne 0 ]; then
+		log_warn "$TESTNAME: failed to execute ifdown on gfsd2"
+		return $RESULT_FATAL
+	fi
+
+	wait $READ_PID1
 	if [ $? -eq 0 ]; then
-		log_warn "$TESTNAME: unexpectedly suceeded to make a file"
+		log_warn "$TESTNAME: unexpectedly suceeded to read a file" \
+			"on gfsd1"
+		RESULT=$RESULT_XPASS
+	fi
+
+	wait $READ_PID2
+	if [ $? -eq 0 ]; then
+		log_warn "$TESTNAME: unexpectedly suceeded to read a file" \
+			"on gfsd2"
 		RESULT=$RESULT_XPASS
 	fi
 
@@ -63,25 +94,27 @@ test_gfsd_ifdown_in_write()
 		return $RESULT_FATAL
 	fi
 
-	# step: make files
-	GFARM_FILE2=$MOUNT_POINT/${TEST_EXEC_ID}_2
-	$GFSERVICE $DEBUG make_file client1 $GFARM_FILE2 $FILE_SIZE
+	$GFSERVICE $DEBUG ifup gfsd2
 	if [ $? -ne 0 ]; then
-		log_warn "$TESTNAME: failed to write files"
+		log_warn "$TESTNAME: failed to execute ifup on gfsd2"
+		return $RESULT_FATAL
+	fi
+
+	# step: read files
+	$GFSERVICE $DEBUG read_file client1 $FILE_PATH1 $CHECKSUM
+	if [ $? -ne 0 ]; then
+		log_warn "$TESTNAME: failed to read files from gfsd1"
 		RESULT=$RESULT_FAIL
 	fi
 
-	GFARM_FILE3=$GFARM_HOME/${TEST_EXEC_ID}_3
-	echo $TEST_EXEC_ID | $GFSERVICE $DEBUG read_and_register client1 \
-		$GFARM_FILE3 gfmd1 gfsd1
+	$GFSERVICE $DEBUG read_file client1 $FILE_PATH2 $CHECKSUM
 	if [ $? -ne 0 ]; then
-		log_warn "$TESTNAME: failed to write files"
+		log_warn "$TESTNAME: failed to read files from gfsd2"
 		RESULT=$RESULT_FAIL
 	fi
 
 	# cleanup: remove files
-	$GFSERVICE $DEBUG exec_ssh client1 rm -f $GFARM_FILE2
-	$GFSERVICE $DEBUG gfcmd client1 gfrm -f $GFARM_FILE1 $GFARM_FILE3
+	$GFSERVICE $DEBUG exec_ssh client1 rm -r $FILE_PATH
 
 	# cleanup: unmount
 	$GFSERVICE $DEBUG umount client1 $MOUNT_POINT
